# Generated by Django 5.1.4 on 2025-06-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airport'),
        ),
    ]
