
name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: installing python
              uses: actions/setup-django@v5
              with: 
                django-version: '5.2.x'
            - name: Run Django unit tests 
              run:
                python manage.py test
