
name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: installing python
              uses: actions/setup-python@v1
              with: 
                python-version: '3.13.x'
            - name: Run Django unit tests 
              run:
                pip install --user django
                python manage.py test
